// Generated by CoffeeScript 1.6.3
(function() {
  window.load_compete = function() {
    return $.getScript("compete/game.min.js", function() {
      return $.getScript("compete/lib/API.js", function() {
        return $.getScript("compete/lib/jquery-ui.js", function() {
          return $.getScript("compete/lib/hintinit.js");
        });
      });
    });
  };

}).call(this);
