// Generated by CoffeeScript 1.6.3
(function() {
  window.handle_login = function() {
    return $.ajax({
      type: "POST",
      cache: false,
      url: "/api/login",
      dataType: "json",
      data: {
        'teamname': $("#reg-team").val(),
        'password': $("#reg-pass").val()
      }
    }).done(function(data) {
      var alert_class;
      if (data['success'] === 0 || data['success'] === 2) {
        if (typeof Storage !== "undefined") {
          sessionStorage.signInStatus = "notLoggedIn";
        }
        if (data['success'] === 0) {
          alert_class = 'alert-error';
        } else if (data['success'] === 2) {
          alert_class = 'alert-info';
        }
        $('#login_msg').hide().html("<div class=\"alert " + alert_class + "\"> " + data['message'] + " </div>").slideDown('normal');
        return setTimeout(function() {
          return $('#login_msg').slideUp('normal', function() {
            return $('#login_msg').html('').show();
          });
        }, 2000);
      } else if (data['success'] === 1) {
        if (typeof Storage !== "undefined") {
          sessionStorage.signInStatus = "loggedIn";
        }
        return document.location.href = "compete";
      }
    });
  };

  window.handle_forgot_password_submit = function() {
    return $.ajax({
      type: "POST",
      cache: false,
      url: "/api/requestpasswordreset",
      dataType: "json",
      data: {
        'teamname': $("#reg-team").val()
      }
    }).done(function(data) {
      var alert_class, login_msg;
      login_msg = $('#login_msg');
      if (data['success'] === 0) {
        alert_class = "alert-error";
      } else if (data['success'] === 1) {
        alert_class = "alert-success";
      }
      login_msg.hide().html("<div class=\"alert " + alert_class + "\"> " + data["message"] + " </div>").slideDown('normal');
      return setTimeout(function() {
        return login_msg.slideUp('normal', function() {
          return login_msg.html('').show();
        });
      }, 3000);
    });
  };

}).call(this);
