// Generated by CoffeeScript 1.6.3
(function() {
  window.load_news = function() {
    return $.ajax({
      type: "GET",
      cache: false,
      url: "/api/news"
    }).done(function(data) {
      var d, date, date_string, day, html, month, months, raw_date_string, year, _i, _len;
      html = '';
      months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        d = data[_i];
        html += '<h3>' + d['header'];
        try {
          raw_date_string = d['date'];
          date_string = raw_date_string.split(" ")[0];
          date = new Date(Date.parse(date_string));
          day = date.getDate();
          month = date.getMonth();
          year = date.getFullYear();
          html += ' - ' + String(months[month] + ' ' + day + ', ' + year);
        } catch (_error) {}
        html += '</h3>';
        html += '<div class="news_article">' + d['articlehtml'] + '</div>';
      }
      return $("#news_holder").html(html);
    });
  };

}).call(this);
