// Generated by CoffeeScript 1.6.3
(function() {
  window.handle_new_password_submit = function() {
    var password, token;
    password = $("#new-pass").val();
    token = window.location.hash.slice(1);
    $.ajax({
      type: "POST",
      cache: false,
      url: "/api/resetpassword",
      dataType: "json",
      data: {
        token: token,
        newpw: password
      }
    }).done(function(data) {
      var alert_class;
      if (data['status'] === 0) {
        alert_class = "alert-error";
      } else if (data['status'] === 1) {
        alert_class = "alert-success";
      }
      $('#pass_reset_msg').hide().html("<div class=\"alert " + alert_class + "\">" + data['message'] + "</div>").slideDown('normal');
      return setTimeout(function() {
        return $('#pass_reset_msg').slideUp('normal', function() {
          return $('#pass_reset_msg').html('').show();
        });
      }, 3000);
    });
    return false;
  };

}).call(this);
