// Generated by CoffeeScript 1.6.3
(function() {
  var clear, fields, getRegData;

  fields = ['email', 'team', 'name', 'aff', 'pass'];

  clear = function() {
    var field, _i, _len, _ref;
    _ref = fields.concat(['group']);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      field = _ref[_i];
      $('#reg-' + field).val('');
    }
    $('#reg_group_vis_toggle').slideUp('fast');
    return $('#join-button').fadeOut('fast', function() {
      return $('#register-button').fadeIn('fast');
    });
  };

  getRegData = function() {
    var field, post, _i, _len, _ref;
    post = {};
    _ref = fields.concat(['group']);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      field = _ref[_i];
      post[field] = $('#reg-' + field).val();
    }
    return post;
  };

  $(document).ready(function() {
    $('#reg-email').focus();
    $('#register-button').click(function(event) {
      var hash, post;
      event.preventDefault();
      hash = window.location.hash;
      post = getRegData();
      if (post['group'] === '' && hash.indexOf("#") !== -1) {
        post['group'] = hash.substring(hash.indexOf("#") + 1);
        post['joingroup'] = 'true';
      }
      return $.ajax({
        type: 'POST',
        url: '/api/register',
        dataType: 'json',
        data: post
      }).done(function(data) {
        var field, _i, _len, _ref, _results;
        if (data['status'] === 0) {
          return $.ambiance({
            message: data['message'],
            type: 'error',
            timeout: 10
          });
        } else if (data['status'] === 1) {
          $.ambiance({
            message: data['message'],
            type: 'success',
            timeout: 7
          });
          return clear();
        } else if (data['status'] === 2) {
          $.ambiance({
            message: data['message'],
            timeout: 5
          });
          $('#register-button').fadeOut('fast', function() {
            return $('#join-button').fadeIn('fast');
          });
          _ref = fields.concat(['group']);
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            field = _ref[_i];
            _results.push($('#reg-' + field).change(function() {
              var _j, _len1, _ref1;
              _ref1 = fields.concat(['group']);
              for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                field = _ref1[_j];
                $('#reg-' + field).unbind('change');
              }
              return $('#join-button').fadeOut('fast', function() {
                return $('#register-button').fadeIn('fast');
              });
            }));
          }
          return _results;
        }
      });
    });
    $('#create_group_link').click(function(event) {
      event.preventDefault();
      return $('#reg_group_vis_toggle').slideDown('fast');
    });
    return $('#join-button').click(function(event) {
      var post;
      event.preventDefault();
      post = getRegData();
      post['joingroup'] = 'true';
      return $.ajax({
        type: 'POST',
        url: '/api/register',
        dataType: 'json',
        data: post
      }).done(function(data) {
        if (data['status'] === 0) {
          return $.ambiance({
            message: data['message'],
            type: 'error',
            timeout: 10
          });
        } else if (data['status'] === 1) {
          $.ambiance({
            message: data['message'],
            type: 'success',
            timeout: 5
          });
          return clear();
        }
      });
    });
  });

}).call(this);
