// Generated by CoffeeScript 1.6.3
(function() {
  window.load_scoreboards = function() {
    console.log("loading scoreboards...");
    return $.ajax({
      type: "GET",
      cache: false,
      url: "/api/scoreboards",
      dataType: "json"
    }).done(function(data) {
      var d, group, html_scores, html_select, idx, s, _i, _j, _len, _len1, _ref;
      html_select = '';
      html_scores = '';
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        d = data[_i];
        if (d['path'] != null) {
          group = d.group;
          $.ajax({
            type: "GET",
            url: d['path'],
            dataType: "html",
            cache: false,
            async: true
          }).done(function(stat) {
            if (group === 'Public') {
              return $('#public_scoreboard_container').html(stat);
            } else {
              html_select += "<li><a onclick=\"switch_scoreboard('" + group + "');\">" + group + "</a></li>";
              return html_scores += "<div style='display: none;' id='scoreboard_" + group + "' class='scoreboard'>" + stat + "</div>";
            }
          });
        } else {
          html_select += "<li><a onclick=\"switch_scoreboard('" + d.group + "');\">" + d.group + "</a></li>";
          html_scores += "<div style='display: none;' id='scoreboard_" + d.group + "' class='scoreboard'><table class='table'><tbody><tr><th>Place</th><th>Team</th><th>Affiliation</th><th>Score</th></tr>";
          _ref = d['scores'];
          for (idx = _j = 0, _len1 = _ref.length; _j < _len1; idx = ++_j) {
            s = _ref[idx];
            html_scores += "<tr><td>" + (idx + 1) + "</td><td class='teamname'>" + s['teamname'] + "</td><td class='affiliation'>" + s['affiliation'] + "</td><td>" + s['score'] + "</td></tr>";
          }
          html_scores += "</tbody></table></div>";
        }
      }
      $('#scoreboard_selector').html(html_select);
      $('#scoreboard_container').html(html_scores);
      if (!!window.location.hash) {
        return !switch_scoreboard(window.location.hash.substr(1));
      } else {
        return $('div.scoreboard').first().slideDown('fast');
      }
    });
  };

  window.switch_scoreboard = function(group) {
    if ($("#scoreboard_" + group).length > 0) {
      window.location.hash = "#" + group;
      if ($("div.scoreboard:visible").length > 0) {
        $("div.scoreboard:visible").slideUp('fast', function() {
          return $("#scoreboard_" + group).slideDown('fast');
        });
      } else {
        $("#scoreboard_" + group).slideDown('fast');
      }
    } else {
      $('div.scoreboard').first().slideDown('fast');
    }
    return false;
  };

  window.load_solved_problems = function() {
    return $.ajax({
      type: "GET",
      cache: false,
      url: "/api/problems/solved",
      dataType: "json"
    }).done(function(data) {
      var d, html, _i, _len;
      html = '<table class=\"table\">';
      if (data.length !== 0) {
        html += "<tr><th>Points Awarded</th><th>Solved Problem</th></tr>";
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          d = data[_i];
          html += "<tr><td>" + d['basescore'] + "</td><td>" + d['displayname'] + "</td></tr>";
        }
        html += "</table>";
        return $("#problems_solved").html(html);
      } else {
        html += "You haven't solved any problems yet.";
        return $("#problems_solved").html(html);
      }
    });
  };

  window.load_teamscore = function() {
    return $.ajax({
      type: "GET",
      cache: false,
      url: "/api/score",
      dataType: "json"
    }).done(function(data) {
      return $('#team_status').html("<h3>Team Status - " + data['score'] + "</h3>");
    });
  };

}).call(this);
