// Generated by CoffeeScript 1.6.3
(function() {
  var handle_teamname_lookup_submit;

  handle_teamname_lookup_submit = function() {
    $.ajax({
      type: "POST",
      cache: false,
      url: "/api/lookupteamname",
      dataType: "json",
      data: {
        email: $('#forgot-email').val()
      }
    }).done(function(data) {
      var alert_class, frgt_msg_div;
      frgt_msg_div = $('#forgot_msg');
      if (data['status'] === 0) {
        alert_class = 'alert-error';
      } else if (data['status'] === 1) {
        alert_class = 'alert-success';
      }
      frgt_msg_div.hide().html('<div class="alert ' + alert_class + '">' + data['message'] + '</div>').slideDown('normal');
      return setTimeout(function() {
        return frgt_msg_div.slideUp('normal', function() {
          return frgt_msg_div.html('').show();
        });
      }, 4000);
    });
    return false;
  };

}).call(this);
