// Generated by CoffeeScript 1.6.3
(function() {
  window.load_webshell_creds = function() {
    return $.ajax({
      type: "GET",
      cache: false,
      url: "/api/getsshacct"
    }).done(function(data) {
      return $("#webshell_credentials").html('<p>Username: ' + data['username'] + '    Password: ' + data['password'] + ' | ssh ' + data['username'] + '@shell.picoctf.com</p>');
    });
  };

}).call(this);
