#!/bin/bash

ROOT=/vagrant/ctf-infrastructure

# Transpile the CoffeeScript files
echo "Transpiling Coffeescript"
cjsx -bc -o $ROOT/web/js/ $ROOT/web/coffee/

# Shutdown the server
echo "Shutting down nginx"
sudo service nginx stop

# Clean out the old files
echo "Cleaning up old files"
sudo rm -rf /srv/http/ctf/*

echo "Generating web with Jekyll"
cd $ROOT/web
sudo jekyll build

# Make sure everything is in UNIX format.
sudo dos2unix -q /srv/http/ctf/*.html

# Start the server
echo "Restarting the server"
sudo service nginx start

# Clear the cache
echo "Clearing the API cache"
$ROOT/api/api_manager.py database clear cache

START_CMD="python3 run.py"
if [[ $1 = "production" ]]; then
    START_CMD="./gunicorn_start.sh"
fi

#Start Cyberstakes API
echo "Starting the Cyberstakes API"
tmux kill-session -t cyberstakesapi 2> /dev/null
tmux new-session -s cyberstakesapi -d "cd $ROOT/api && $START_CMD"

#Start Stats caching daemon
echo "Starting the statistics caching daemon"
tmux kill-session -t cyberstakesstats 2> /dev/null
tmux new-session -s cyberstakesstats -d "cd $ROOT/api && python3 daemon_manager.py cache_stats"
