---
# Playbook that installs and configures services on the shell_server

# Extracted from picoCTF-platform/scripts/shell_setup.sh
- name: Template shellinaboxd Service file
  template: 
    src: "shellinaboxd.service.j2"
    dest: "/lib/systemd/system/shellinaboxd.service"
    owner: root
    group: root
    mode: 0644

- name: Enable shellinaboxd Service
  service:
    name: "shellinaboxd.service"
    enabled: yes

- name: Start shellinaboxd Service
  service:
    name: "shellinaboxd.service"
    state: started

- name: Copy over pam configs
  copy:
    src: common-auth
    dest: /etc/pam.d/common-auth
    owner: root
    group: root
    mode: 0644

- name: Ensure /lib/security/ directory exists
  file:
    path: /lib/security/
    state: directory
    owner: root
    group: root

- name: Copy pam_auth.py to deployed location
  copy:
    src: pam_auth.py
    dest: "/lib/security/pam_auth.py"
    owner: root
    group: root
    mode: 0644

- name: Copy over sshd configs
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: Restart ssh service to pickup new configs
  service:
    name: sshd
    state: restarted

- name: Add competitiors group
  group: 
    name: competitors
    state: present
